### ISSUE TITLE
building-from-source_wrong-setuptools-called??

### ISSUE THREAD

**Issue by brobr** [simon-anders/htseq#101]
Hi, when I was building HTSeq completely from source, using `python3 setup.py install`,
a warning popped up which could be related to this setuptools/pip issue: 
[https://github.com/pypa/setuptools/issues/1458:](url)

It's put in their hands:
[https://github.com/pypa/setuptools/issues/2066](url)

By doing so, I assumed there's no call for `pip` or `pip2` during building the program  with python3. Is that correct?

**Comment by iosonofabio** [comment]
Please file a bug on the new official repo: https://github.com/htseq/htseq Sorry about the inconvenience. Also include what warming you get.

**Comment by brobr** [comment]
Whell, that repo is novel (at least to me). Also, maybe you can move this there when you have set up an issues section. And the code example you find when you copy paste the link address; the links don't work here (anymore?)

**Comment by brobr** [comment]
Before advising others, you want to redirect them first:
Please update on [https://pypi.org/project/HTSeq/](https://pypi.org/project/HTSeq/)
Home-page liink: [https://github.com/simon-anders/htseq](url)

And under Project description
Development: [https://github.com/simon-anders/htseq](https://github.com/simon-anders/htseq)

**Comment by iosonofabio** [comment]
This issue is closed, but thank you for the advice.

Unfortunately I don't have time to reopen issues for people. Please open a new one on that repo as requested before, thank you for your understanding.
