### ISSUE TITLE
Issues on htseq/htseq?

### ISSUE THREAD

**Issue by ewallace** [simon-anders/htseq#102]
The documentation site still points to this repository [simon-anders/htseq](https://github.com/simon-anders/htseq/). See for example the Github link on [install help page](https://htseq.readthedocs.io/en/master/install.html). 

This repo's new repo says "No issues on this repo will be addressed anymore".

But [the new htseq/htseq repo](https://github.com/htseq/htseq) doesn't seem to have an "issues" tab showing. Can that be added to the repo settings?

**Comment by iosonofabio** [comment]
thank you, done, closing.
