### ISSUE TITLE
HTseq-count --strand parameter for TruSeq RNA Exome

### ISSUE THREAD

**Issue by tdfy** [simon-anders/htseq#106]
Hello, 

I observed a high percentage of "no features" while running HTseq w/ the --stranded yes option enabled (>80%). The library prep kit I am using is [Illumina TruSeq RNA Exome](https://www.kumc.edu/Documents/gsf/Illumina%20TruSeq%20RNA%20Exome%20User%20Guide.pdf) which generates stranded data. If I run HTseq-count w/ strand == "no" or "reverse" I observe expected levels of "no features" <2%. 

I have checked for compatibility between reference genome and gtf coordinates (chr1 vs 1) and mapped to a second reference genome to assure gtf ranges are concordant.

I came across this [paper ](https://www.preprints.org/manuscript/201903.0124/v1) describing the best option to call based on strand synthesis. The Illumina guide describes the molecular reactions as, 

```
The RNA is fragmented using divalent cations under elevated temperature. cDNA is generated from the
cleaved RNA fragments using random priming during first and second strand synthesis. Then, sequencing
adapters are ligated to the resulting double-stranded cDNA fragments. The coding regions of the
transcriptome are captured from this library using sequence-specific probes to create the final library.
```

Can you please advise on the best --stranded option for this chemistry? Thank you. 

-T

CFLAR (+ strand)
![igv_panel](https://user-images.githubusercontent.com/25744474/129415949-cace3f65-22bb-4c05-b257-85f3c2ee367f.png)

**Comment by simon-anders** [comment]
If I recall correctly, "reverse" is correct for TruSeq, because TrueSeq reads are 3' to 5', i.e. reverse to the "biological" reading direction.

That the non-reversed direction is called "yes" rather than "forward" hast historical reasons: When I write that, TruSeq did not exist yet, and the first stranded protocols where 5' to 3'.

**Comment by simon-anders** [comment]
To be more precise: Read 1 is 3' to 5'. Read 2 is the opposite direction, of course. For paired-end reads, the "stranded" parameter should describe the orientation of read 1.

**Comment by tdfy** [comment]
thank you so much, take care
