### ISSUE TITLE
matplotlib.normalize

### ISSUE THREAD

**Issue by simon-anders** [simon-anders/htseq#2]
_Adam Tebbe wrote:_

Hello Simon,

I was trying out your HTSeq library (installed version 0.6.1 from the public pypi repository).  I am specifically trying out the htseq-qa script and have found that it does not run as expected.

Traceback (most recent call last):
  File "/usr/local/bin/htseq-qa", line 5, in <module>
    HTSeq.scripts.qa.main()
  File "/usr/local/lib/python2.7/site-packages/HTSeq/scripts/qa.py", line 204, in main
    norm=pyplot.normalize( 0, 1 ) )
AttributeError: 'module' object has no attribute 'normalize'

I found that in version 1.5.1 of matplotlib, this call should be pyplot.Normalize instead of pyplot.normalize.  There are three places in HTSeq/scripts/qa.py where this call is made.  

I noticed that the code repository is hosted svn, which I have not used in many years.  I’m happy to contribute a patch file or updated code if this would be helpful to try to correct this issue.

Thanks,
Adam Tebbe
Immuneering Corporation

**Comment by iosonofabio** [comment]
A fix that is compatible with both versions of matplotlib is waiting in a [branch](https://github.com/iosonofabio/htseq/tree/pyplotNormalize) on my repo. As soon as pull requests #14 and #15 get accepted we can proceed with this fix too.

**Comment by iosonofabio** [comment]
fixed in  ec96f5f
