### ISSUE TITLE
HTSeq: Failed to import 'numpy'. when building snap

### ISSUE THREAD

**Issue by dmnfarrell** [simon-anders/htseq#25]
Hi

I am trying to build a snap package on Ubuntu that includes HTSeq. It seems to be the only thing that won't work. I get the following error:
```
Setup script for HTSeq: Failed to import 'numpy'.
Please install numpy and then try again to install HTSeq.
```

Obviously numpy and other dependencies are being installed as well and the package is installed on my normal system. This is using python 2.7. Could there be something else missing that is falsely flagged as a numpy error? You might not be familiar with snaps but I do think it's a HTSeq problem as all the other packages build ok.
Any ideas?

**Comment by iosonofabio** [comment]
Hi Damien,
Thanks for your efforts! Have you checked the Travis CI tests for HTSeq to get a sense whether you are missing something in the dependency chain? 

I am not familiar with snaps, a link would help. However, I have included HTSeq in a number of docker images without problems... Maybe the numpy shared libs or header files? HTSeq does need both to compile.

Can you provide a link to an automated build that's making the snap or is it you typing the commands manually in a shell?

Thanks!

**Comment by dmnfarrell** [comment]
Hi Fabio
Yes I must have missed some dependency that is present on my main system. snaps can build a python package using the setup.py but you can also specify ubuntu apt packages (i.e. python-numpy) before installing the pypi dependencies and that seems to work. I'll mark this as fixed. cheers.

https://snapcraft.io/docs/reference/plugins/python

**Comment by iosonofabio** [comment]
Thanks for the link!
