### ISSUE TITLE
SAM_Alignment :  not_primary_alignment not taking flag 0x800 into account

### ISSUE THREAD

**Issue by FrozenTux** [simon-anders/htseq#26]
Hello,

In the SAM_Alignment class, the not_primary_alignment attribute only takes the flag 0x100 into account to determine whether a read is primary or not. However, the SAM spec also defines flag 0x800 as "supplementary alignment". This flag is used by programs such as BWA-MEM to mark other alignments reported for the same read, which would fit the definition of "not primary". 

I think either the presence of this flag should make not_primary_alignment true, or the variable should be renamed to avoid confusion.

On a related note, in [the documentation](http://htseq.readthedocs.io/en/master/alignments.html#HTSeq.SAM_Alignment.nor_primary_alignment) , the attribute is spelled "nor_primary_alignment" instead of "not_primary_alignment".

Version : HTSeq 0.7.2 (from Pypi) on Python 3.5

**Comment by iosonofabio** [comment]
Thanks will look into this ASAP

**Comment by iosonofabio** [comment]
Ok I typoed the docs that's done. Hmmm SAM has 0x100 and 0x800 and 0x900 now. And those have blurred definitions and are used organically by various tools. Great.

We rely on `pysam` to get whether a read is a primary alignment, a secondary alignment, or what else, and `pysam` has broken documentation as well:

http://pysam.readthedocs.io/en/latest/api.html?highlight=is_secondary#pysam.AlignedSegment.is_secondary

so we should ping them about this subtlety (@FrozenTux could you please do that?). For now I am going to change the documentation to "secondary alignment" and add separate support for supplementary alignments, but leave the issue open.

**Comment by FrozenTux** [comment]
> Ok I typoed the docs that's done. Hmmm SAM has 0x100 and 0x800 and 0x900 now. And those have blurred definitions and are used organically by various tools. Great.

Bioinformatics in a nutshell

> so we should ping them about this subtlety (@FrozenTux could you please do that?).

Ok, I'll do that.

Thanks for the help and timely response !

**Comment by iosonofabio** [comment]
Added support in release 0.8.0
