### ISSUE TITLE
pickling does not work

### ISSUE THREAD

**Issue by mjoppich** [simon-anders/htseq#30]
Thank you very much for supporting python3!

In the python3 release (pip) pickling does not seem to work with neither pickle nor dill.

The unpickled object always reports: "Unable to get repr for <class 'HTSeq._HTSeq.Sequence'>"

I hope you can solve this issue as otherwise multiprocessing does not make too much fun :(

**Comment by iosonofabio** [comment]
Hi mjoppich,
thanks for the report, I'll have a look asap!

**Comment by iosonofabio** [comment]
Hej mjoppich,

Actually I cannot even pickle, not only unpickle. Can you run this?

```python
import pickle
import HTSeq
with open('tmpfile.pickle', 'w') as f:
    pickle.dump(HTSeq.Sequence(b'ACTG', 'seq'), f)
```
Thanks!
Fabio

**Comment by iosonofabio** [comment]
OK `HTSeq.Sequence` is a Cython class and Cython does not support `pickle` automatically. I will add support for this in the next release.

**Comment by mjoppich** [comment]
I am currently using a simple work around by "saving" things in a python object (which however might be slow as hell/consume loads of RAM, depending on how you implemented it ...).

```
class MinSeq:

    def __init__(self, seq, name, desc):

        self.seq = seq
        self.name = name
        self.desc = desc

    def toHTSeq(self):

        htseq = HTSeq.Sequence(self.seq, self.name)
        htseq.descr = self.desc

        return htseq
```

dumping it seems to work quite fine (you must write a binary file):
`pickle.dump(self.fasta[x], open("/tmp/bla", 'wb'))`

Cheers from Munich!

**Comment by iosonofabio** [comment]
I added support in the dev branch but I'm still fixing it for python 2, expected for the next release

**Comment by iosonofabio** [comment]
fixed in the dev branch, closing
