### ISSUE TITLE
Problem getting part of sequence

### ISSUE THREAD

**Issue by osvaldoreisss** [simon-anders/htseq#31]
Hey Guys, thanks for the great job in this Library. I wanted ask for help to solve this problem. I'm trying to get part  of a sequence using an interval from SAM file.

This part of my code:

```
genome = HTSeq.FastaReader(genome)
sam = HTSeq.SAM_Reader(sam)
    for line in sam:
        read = None 
        read = line.iv.copy()
        if read.strand == '+':
            read.strand = '-'
            read.end = read.start +1
            read.start = read.start -10
        elif read.strand == '-':
            read.strand = '+'
            read.start = read.end+1
            read.end = read.end +12
        print(genome[read].seq)
```
and I'm getting this error:

```
Traceback (most recent call last):
  File "filter.py", line 89, in <module>
    main()
  File "filter.py", line 85, in main
    filter(args.genome, args.sam)
  File "filter.py", line 59, in filter
    print(genome[read].seq)
  File "/usr/lib64/python3.4/site-packages/HTSeq-0.8.0-py3.4-linux-x86_64.egg/HTSeq/__init__.py", line 357, in __getitem__
    ans = list( FastaReader( fasta ) )
  File "/usr/lib64/python3.4/site-packages/HTSeq-0.8.0-py3.4-linux-x86_64.egg/HTSeq/__init__.py", line 290, in __iter__
    for line in FileOrSequence.__iter__( self ):
  File "/usr/lib64/python3.4/site-packages/HTSeq-0.8.0-py3.4-linux-x86_64.egg/HTSeq/__init__.py", line 54, in __iter__
    lines = open( self.fos )
FileNotFoundError: [Errno 2] No such file or directory: '>I:1758-1768\nTTAATTTTCAA\n'
```
It keep the interval sequence in a string, but try to open this string as a file.

Any help would be greatly appreciated.

**Comment by iosonofabio** [comment]
Sure:

- python version
- HTSeq version
- what is "genome" at the start?
- please complete the end of the script are you missing a bracket?

**Comment by osvaldoreisss** [comment]
Ok:

-Python 3.4.5
-HTSeq 0.8.8
- This genome is a string with the name of a FASTA file the S. cereviseae genome sequence
- A had updated the end of the code and correct it.

Thanks,

**Comment by iosonofabio** [comment]
Hi

- 0.8.8 does not exist
- Unicode string or bytestring?

Thx

**Comment by osvaldoreisss** [comment]
Sorry,
- HTSeq 0.8.0
- Unicode string

**Comment by iosonofabio** [comment]
`HTSeq.FastaReader` cannot take a sequence, but only:
- a filename
- an open file handle (in read mode)
- an *iterable* of sequences, e.g. a list of sequences

So try:

```python
sequence_iterator = HTSeq.FastaReader([genome])
```

Changed the official docs which were incorrect:

http://htseq.readthedocs.io/en/master/sequences.html#fastareader

**Comment by osvaldoreisss** [comment]
Hi,

But my variable "genome" is a FASTA filename:

`>>> genome
<FastaReader object, connected to file name './index/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa'>`

I get the error when I try to get an item:

`genome[read].seq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/HTSeq-0.8.0-py3.4-linux-x86_64.egg/HTSeq/__init__.py", line 369, in __getitem__
    ans = list(FastaReader(fasta))
  File "/usr/lib64/python3.4/site-packages/HTSeq-0.8.0-py3.4-linux-x86_64.egg/HTSeq/__init__.py", line 299, in __iter__
    for line in FileOrSequence.__iter__(self):
  File "/usr/lib64/python3.4/site-packages/HTSeq-0.8.0-py3.4-linux-x86_64.egg/HTSeq/__init__.py", line 58, in __iter__
    lines = open(self.fos)
FileNotFoundError: [Errno 2] No such file or directory: '>I:1758-1768\nTTAATTTTCAA\n'`

I'm confuse because when it calls the method:

`def __getitem__(self, iv):
        if not isinstance(iv, GenomicInterval):
            raise TypeError("GenomicInterval expected as key.")
        if not isinstance(self.fos, str):
            raise TypeError("This function only works with FastaReader objects " +
                            "connected to a fasta file via file name")
        self._import_pysam()
        fasta = pysam.faidx(self.fos, "%s:%d-%d" %
                            (iv.chrom, iv.start, iv.end - 1))
        ans = list(FastaReader(fasta))
        assert len(ans) == 1
        ans[0].name = str(iv)
        if iv.strand != "-":
            return ans[0]
        else:
            return ans[0].get_reverse_complement()`

Until this part:

`fasta = pysam.faidx(self.fos, "%s:%d-%d" %
                            (iv.chrom, iv.start, iv.end - 1))`

it return:

`>>> fasta
'>I:1758-1768\nTTAATTTTCAA\n'`

but when call:

`ans = list(FastaReader(fasta))`

raise the error above
