### ISSUE TITLE
htseq-count: my_showwarning() takes from 3 to 5 positional arguments but X were given

### ISSUE THREAD

**Issue by PeterParker1** [simon-anders/htseq#33]
hello! I'm trying to use htseq-count to count reads from sam file, but it always fails.

Error occured when processing SAM input (line 537 of file lnc1-r.sortn.sam):
  my_showwarning() takes from 3 to 5 positional arguments but 6 were given
  [Exception type: TypeError, raised in warnings.py:99]

The script is
#!/bin/bash
#SBATCH -N 1 -c 16
exe=htseq-count
$exe -s no lnc1-r.sortn.sam gencode.all.gtf

I got sam file with hisat2, and the script is

#!/bin/bash
#SBATCH -N 1 -c 16
exe=hisat2
$exe -p 16 -x /data/wu/zeng/RNAseq/lncrna/GRCh38revised/GRCh38r -1 /data/wu/zeng/RNAseq/lncrna/1r/z-1-34_L7_1.clean.fq -2 /data/wu/zeng/RNAseq/lncrna/1r/z-1-34_L7_2.clean.fq -S lnc1-r.sam

I convert sam to bam ,sort by name ,and covert bam to sam.

The genome data and gtf were downloaded from Gencode.

**Comment by iosonofabio** [comment]
Thanks, I've been working on this but got dragged away. You said the bamfile is sorted by name? Can you upload the offending read or read pair please, together with the gff?
Thanks
Fabio

**Comment by PeterParker1** [comment]
Thanks，I used “head -538 lnc1-r.sortn.sam” to get the offending read pair，and I'm not sure whether it's right or not. 
E00477:112:HL7THALXX:7:1101:1385:55720  73      chr14   49862565        60      150M    =       49862565        0       GCTATGTTGCTCAGGCTGGAGTGCAGTGTCTATTCACAGGCGCGATCCCACTACTGATCAGCACGGGAGTATTGACCTGCTCCGCTTCCGACCTGGGCCGGTTCACTCCTCCTTAGGCAACCTGGTGGTCCCCCGCTCCCGGGAGGTCAC  AAFFFAKFFKKKF<A<7F<7F,AFAFKK7F,FFKKF,77AFKFFFA7FF77FAKA,,,,7A,77AF<AA,,77A<FA,FA7F7A(FFA,AAF(,AFFFAFK,<F,F,,,AFF,,,A,FAKKFFFF<F7A7,(,(77,A((,7A(7A,7,<  AS:i:-12        ZS:i:-23        XN:i:0  XM:i:4  XO:i:0  XG:i:0  NM:i:4  MD:Z:28G41T13T21C43     YT:Z:UP NH:i:1
E00477:112:HL7THALXX:7:1101:1385:55720  133     chr14   49862565        0       *       =       49862565        0       NAAGGTGGGAGGATCGCTTGAGACAAGGAGTTATGGGNTGAAGTGCGNCACGCAGANNGGGTGTCCGCACTAAGTTCGGCATCAACATGGCGACCTCCCGGGAGCGGGGGACCACCAGGTTGCCTAAGGAGGGGTGAACCGGCTCAGGTG  #,AA,,AF<7FF7F77,,7AKF77A,FK,7,,,,7FA#,77,FF7,,#,7,A,,FF##FKKA7,<,,(,(,<AFAAA<<,7,,7,,A,,A,F,AAFKKKKFF,AAAFKKK7,AA7FAFK<AA,,,,,,A<FFKK,<,,,,<A,(,,,A,,  YT:Z:UP

And the genome and annotation file I use are ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/gencode.v25.chr_patch_hapl_scaff.annotation.gtf.gz and
ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/GRCh38.p7.genome.fa.gz

**Comment by iosonofabio** [comment]
Please make a bam file with only the header and this pair and check again, I have fixed the warning problem in 9db4215 but I suspect a deeper problem.

Thank you

**Comment by iosonofabio** [comment]
I got it, it is a very painful corner case. Your mapper, hisat2, gives a chromosome to the second of your reads (chr14) although it is unmapped (probably in an attempt to be consistent with the mate read, I don't know). Although this is theoretically supported in the SAM format, I tend to think it's a bad design of the mapper to give a chromosome to an unmapped read, so I'm not sure I should fix this. Please ask the hisat2 folks and see whether they are aware of this and what they say, and let me know.

thanks

**Comment by PeterParker1** [comment]
Many thanks. I'll check the parameter of hisat2 and ask them.

**Comment by PeterParker1** [comment]
Sorry I‘m quite busy these days. I tried another mapper,tophat,and HTSeq reported the same problem. So maybe it's not the question about mapper. I used cufflinks+cuffdiff, cuffnorm+Trinity (Trinity called a program edgeR), and it worked well.

**Comment by iosonofabio** [comment]
Hi Peter,
Thanks but as I told you there were two problems, the warning one will be fixed in 0.9.0. the other problem is why some mappers give a chromosome to unmapped reads, which is what I was wondering you could ask them.

**Comment by iosonofabio** [comment]
as bad as it sounds, the SAM format explicitely allows assigning a chromosome to an unmapped read, so I silenced the warnings lest an overzealous mapper results in endless logs. Fixed in 96639e2. Closing.

**Comment by PeterParker1** [comment]
I asked in the Github about the mapping problem about Hisat2，but unluckily， nobody replied. Thank you very much.
