### ISSUE TITLE
BAM_Reader Error: CIGAR code

### ISSUE THREAD

**Issue by nwaring1** [simon-anders/htseq#35]
Two new characters (‘=’ and ‘X’) have recently been added to the
CIGAR string in SAM/BAM format. When I try to use the HTSeq
BAM_Reader on most BAM files, I get the following error:

File "/Library/Python/2.7/site-packages/HTSeq/__init__.py", line 947,
in __iter__ yield SAM_Alignment.from_pysam_AlignedSegment( pa, sf )
   File "python2/src/HTSeq/_HTSeq.pyx", line 1326, in
HTSeq._HTSeq.SAM_Alignment.from_pysam_AlignedSegment
(src/_HTSeq.c:30549) File "python2/src/HTSeq/_HTSeq.pyx", line 1177,
in HTSeq._HTSeq.build_cigar_list (src/_HTSeq.c:27110) ValueError:
Unknown CIGAR code '=' encountered.

It would be very helpful if you could address this issue in an
update. Page 5 of this document contains the updated CIGAR string:
https://samtools.github.io/hts-specs/SAMv1.pdf

**Comment by iosonofabio** [comment]
Will try, thanks

**Comment by iosonofabio** [comment]
fixed in 16817d3
