### ISSUE TITLE
download HTSeq in windows

### ISSUE THREAD

**Issue by layal-khayal** [simon-anders/htseq#38]
I used HTSeq in Linux,Now I need it in my windows but the modules give this error when I tried to download it.
    os.symlink(py_fdn+fdn, fdn)
AttributeError: 'module' object has no attribute 'symlink'

In stackoverflow I found this answer:
https://stackoverflow.com/questions/1236172/py2app-error-module-object-has-no-attribute-symlink
"os.symlink is only available on Unix and Unix-like operating systems (including the Mac), not Windows."

Is it so?
if is so how can be HTSeq available for windows?
http://htseq.readthedocs.io/en/release_0.9.1/install.html#ms-windows
in 
https://pypi.python.org/pypi/HTSeq#downloads
all the download files for mac and linux, I downloaded the the source file , is this the one which is available for windows?

**Comment by iosonofabio** [comment]
Windows not easy to support since pysam has not automated their builds and I don't have Windows myself. Sorry. Use a virtual machine :-)
