### ISSUE TITLE
htseq-0.9.1 :: make documentation broken due to doc beeing a link

### ISSUE THREAD

**Issue by EricDeveaud** [simon-anders/htseq#39]
Hello, 

while building htsqe-0.9.1 from release archive (https://github.com/simon-anders/htseq/archive/release_0.9.1.tar.gz)

make doc, aka make html  was giving the following error message

```
[gensoft@c467b007697e htseq-release_0.9.1]$ cd doc
[gensoft@c467b007697e doc]$ make html
mkdir -p _build/html _build/doctrees _static
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5.3

Exception occurred:
  File "conf.py", line 52, in <module>
    version = open( "../VERSION" ).readlines()[0].rstrip()
IOError: [Errno 2] No such file or directory: '../VERSION'
```

as doc is a link to python2/doc it is correct that ../VERSION does not exist 

fix was easy via ln -s, but you may want to implement a more clean solution

regards

Eric

**Comment by iosonofabio** [comment]
Thanks for the report, there's some hardwiring that works on readthedocs, where the official docs are hosted anyway. Since you can clone the repo and host it yourself on readthedocs, no big rush to fix.

I accept pull requests though ;-)
