### ISSUE TITLE
Adding ability for using cores

### ISSUE THREAD

**Issue by sdhutchins** [simon-anders/htseq#43]
Have there been any discussions about provide the use of cores with this this program?

**Comment by iosonofabio** [comment]
Hi Shaurita,
Sorry you mean parallel CPUs? Could be done if there's an actual application... What do you need it for?

Thanks
Fabio

**Comment by sdhutchins** [comment]
@iosonofabio yes, in particular, I'm looking to improve the efficiency of `htseq-count`.

**Comment by iosonofabio** [comment]
Could you tell me your application? I've parsed billions of sequencing reads in a matter of minutes, so it's unclear to me in what context htseq is too slow...

**Comment by sdhutchins** [comment]
@iosonofabio I'm trying to use the htseq-count scripts on about 120 bam files (human) and it's been running for roughly 300+ hrs. I'm looking for a way to shorten this - perhaps use the htseq-count script with multiprocessing to send each bam file out, read it, then join it to a final output file.

**Comment by iosonofabio** [comment]
thanks, ok I see the point. The main reason htseq-count is not using multiple cores is that counting genes is a so-called *trivially parallelizable* algorithm. In other words, there are easy workarounds to achieve the same speed boost without messing with concurrency.

In your specific case, here's what you should do:

1. if you're running the 120 bam files one after the other, you should run 120 parallel htseq-count programs instead, using one core for each of them. If you are using a cluster, it's gonna take care of it. If you are doing it on your local machine and it has say 6 cores, you should write a simple wrapper script that launches 6 instances of htseq-count in parallel and starts a new one whenever one is done.

2. if **each** of the 120 bam files takes 300+ hours, you should split them into smaller bam files (say 10 of them), then compure 1200 htseq-count programs in parallel, and then join the count tables at the end.

I do **1.** all the time, and have done **2** in the past for similar reasons. Of course adding multicore support to htseq is an option, but I don't see it happening anytime soon as it's quite a mess to code and concurrent programming is fairly hard to debug.

**Comment by sdhutchins** [comment]
@iosonofabio is there any concern for the counts changing with doing **1**?

**Comment by iosonofabio** [comment]
I do it all the time, you just have to be careful if you merge the counts into a single file at the end but that goes without saying.

**Comment by sdhutchins** [comment]
Thanks for your help. I ended up using method 1 and then using pandas to merge the counts files.

**Comment by iosonofabio** [comment]
good. closing

**Comment by OnlyBelter** [comment]
I still think it is a little bit slow compared with `featureCounts`. 
I am following this nature protocol - "Count-based differential expression analysis of RNA sequencing data using R and Bioconductor", step 13: "count reads using htseq-count",  7 .sam files will take 3 hours, it is too long!

**Comment by iosonofabio** [comment]
Please no necrobumping, this thread is closed. Tldr pull requests are very welcome...
