### ISSUE TITLE
pysam api supporting 

### ISSUE THREAD

**Issue by lozybean** [simon-anders/htseq#44]
I would like to compare the **cigarstring** of two segments, and ** query_alignment_sequence** is very useful to ignore softclip bases. All these properties is in `pysam.AlignedSegment` API, would you like to keep these property?

**Comment by iosonofabio** [comment]
Hi,
Sorry what part of the htseq API are you referring to?
Thanks
Fabio

**Comment by lozybean** [comment]
In `HTSeq.SAM_Alignment` class, I don't know whether it is inherit from `pysam.AlignedSegment`? 
but there is some useful property like `cigarstring`, `query_alignment_sequence` in `pysam.AlignedSegment`  class, can HTSeq do the same things?

**Comment by iosonofabio** [comment]
I'm a bit confused, can you provide a minimal example of what you are trying to do? If you can do it with `pysam` already, what's the matter? `HTSeq` uses pysam anyway...

**Comment by lozybean** [comment]
OK, I just try to use HTSeq only. Thank you and sorry for making you confuse.
