### ISSUE TITLE
memmap_dir not passed on to ChromVector.create

### ISSUE THREAD

**Issue by wkopp** [simon-anders/htseq#48]
Hi,

I found that when creating a `GenomicArray` according to
`GenomicArray(chromsize, stranded=False, storage='memmap', memmap_dir='my/path')`
the .nmm files are be created in the current directory `./` instead of
in the desired folder `my/path`.

I have solved this issue in PR #46 .

Best,
Wolfgang

**Comment by iosonofabio** [comment]
I'll try and have a look today (PCT).
Thank you

**Comment by iosonofabio** [comment]
Thank you! Merged. Closing
