### ISSUE TITLE
GFF_Reader does not take unicode str

### ISSUE THREAD

**Issue by jeremywzh** [simon-anders/htseq#50]
Given a unicode string gtf path , GFF_Reader will report an error when trying to iterate the feature in it.

In "FileOrSequence" class, the following code:
 def __iter__( self ):
      self.line_no = 1
      if isinstance( self.fos, str ):
         if self.fos.lower().endswith( ( ".gz" , ".gzip" ) ):
            lines = gzip.open( self.fos, 'rt' )
         else:
            lines = open( self.fos )
      else:
         lines = self.fos

The problem is " if isinstance( self.fos, str ):", it should be  "if isinstance( self.fos, basestring ):", in order to cover both 'str' and 'unicode'.

**Comment by iosonofabio** [comment]
Fixed in git version, a release on pip will follow as soon as I find the time. Thanks for reporting.
