### ISSUE TITLE
* in column 7 of sam is not recognized

### ISSUE THREAD

**Issue by jtmieg** [simon-anders/htseq#51]
In SAM files, one often encounters a * in column 7, and this is in conformity with the SAM specification. HTseq crashes on the *. If you replace the * by a zero 0 in column 7, then HTseq is happy.
I suggest that HTseq should accept the * in column 7, but have not studied all the consequences.
What do you think
Thank you

**Comment by fbucchini** [comment]
Hi jtmieg, 

Have you managed to find another workaround? I am also experiencing this issue.

**Comment by iosonofabio** [comment]
OK guys, let's try to get this done. Either of you has a minimal example?

Is this referring to htseq-count or to HTSeq as a library? If the latter, what function fails and what's the error message?

Thanks

**Comment by jtmieg** [comment]
Hello Fabio

I used a workaround in my python code
As you can see i pipe the output of samtools  through a gawk which removes the * in column 7 and replaces it by a zero
Then i can use
import HTSeq
for a in HTSeq.SAM_Reader( input_stream ):
    analyze the alignement in python

this is clearly suboptimal, but it works
i am not sure why i had a * in column 7 in the first place, but this came out of using several aligners (star, tophat2, hisat2
at least one of them gave me a *

it is great if you can just add this replacement in silent mode inside   « HTSeq.SAM_Reader( input_stream )

thanks for maintaining the code
jean


# Select the input stream
gg =  """ gawk -F '\\t' '{gsub("*","0",$7);printf("%s",$1);for(i=2;i<=NF;i++)printf("\\t%s",$i);printf("\\n");}' """

if input_file == "":
                input_stream = os.popen( " sort -k 1,1 ")
                # sys.stdin
else:
                if file_type == "BAM":
                                input_stream = os.popen( "samtools view -h " + input_file + " | " + gg + " | sort -T . -k 1,1 ")
                elif file_type == "SAMSORTED":
                                input_stream = open(input_file, "r") ;
                elif file_type == "SAMGZ":
                                input_stream = os.popen( "gunzip -c " + input_file +  " | " + gg + " | sort -T . -k 1,1 ")
                else:
                                input_stream = os.popen( "cat " + input_file + " | " + gg + " | sort -T . -k 1,1 ")

**Comment by iosonofabio** [comment]
1. Python 2 or 3?
2. Are these reads illumina paired end?

**Comment by fbucchini** [comment]
Hi Fabio,

For me this problem occurred when I was using the `htseq-count` script. However, I think that it was simply a conflict between two HTSeq versions on my system, since I  don't experience this problem anymore after a clean install (with version `0.9.1`).

**Comment by iosonofabio** [comment]
ok guys, seems like you solved on your own, closing until further notice
