### ISSUE TITLE
--nonunique all

### ISSUE THREAD

**Issue by dws23** [simon-anders/htseq#54]
Hi, I have been trying to get the counts for features that are very close together, but reads will likely overlap (ChIP-seq, not RNA). I have been having errors when I try to use the --nonunique option. This is the error I get:

$ htseq-count -f bam -r pos -s reverse -t transcript -i transcript_id --nonunique-all ARPE19_ChIP_Control01.final.sorted.bam /projects/scratch/skcm/ARPE19/RNA/Homo_sapiens.GRCh38.90.gtf >> Control_01.reverse.transcript.counts.txt

Usage: htseq-count [options] alignment_file gff_file

htseq-count: error: no such option: --nonunique-all

I have tried updating my version with pip install --upgrade HTSeq, but I am still getting the error. I am using Python 2.7.3. 

Is there a solution for this?

Thank you,

Dave

**Comment by iosonofabio** [comment]
Sorry what version of htseq are you using?

**Comment by iosonofabio** [comment]
BTW there's no dash btw "--nonunique" and "all"

**Comment by dws23** [comment]
Hi, thank you for the quick response. I thought it was update to 0.9.0, I did this using  pip upgrade, but it said the version was current.


login4->[/projects/scratch/skcm/ARPE19/RNA]$ pip install HTSeq
Requirement already satisfied (use --upgrade to upgrade): HTSeq in /nethome/dws23/VirtualPython/ENV/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy in /nethome/dws23/VirtualPython/ENV/lib/python2.7/site-packages (from HTSeq)
Requirement already satisfied (use --upgrade to upgrade): pysam>=0.9.0 in /nethome/dws23/VirtualPython/ENV/lib/python2.7/site-packages (from HTSeq)
You are using pip version 8.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
login4->[/projects/scratch/skcm/ARPE19/RNA]$ pip install --upgrade HTSeq
Requirement already up-to-date: HTSeq in /nethome/dws23/VirtualPython/ENV/lib/python2.7/site-packages

But when I run the prompt with no options, it says version 0.6.0

login4->[/projects/scratch/skcm/ARPE19/RNA]$ htseq-count
Usage: htseq-count [options] alignment_file gff_file

This script takes an alignment file in SAM/BAM format and a feature file in
GFF format and calculates for each feature the number of reads mapping to it.
See http://www-huber.embl.de/users/anders/HTSeq/doc/count.html for details.

Options:
  -h, --help            show this help message and exit
  -f SAMTYPE, --format=SAMTYPE
                        type of <alignment_file> data, either 'sam' or 'bam'
                        (default: sam)
  -r ORDER, --order=ORDER
                        'pos' or 'name'. Sorting order of <alignment_file>
                        (default: name). Paired-end sequencing data must be
                        sorted either by position or by read name, and the
                        sorting order must be specified. Ignored for single-
                        end data.
  -s STRANDED, --stranded=STRANDED
                        whether the data is from a strand-specific assay.
                        Specify 'yes', 'no', or 'reverse' (default: yes).
                        'reverse' means 'yes' with reversed strand
                        interpretation
  -a MINAQUAL, --minaqual=MINAQUAL
                        skip all reads with alignment quality lower than the
                        given minimum value (default: 10)
  -t FEATURETYPE, --type=FEATURETYPE
                        feature type (3rd column in GFF file) to be used, all
                        features of other type are ignored (default, suitable
                        for Ensembl GTF files: exon)
  -i IDATTR, --idattr=IDATTR
                        GFF attribute to be used as feature ID (default,
                        suitable for Ensembl GTF files: gene_id)
  -m MODE, --mode=MODE  mode to handle reads overlapping more than one feature
                        (choices: union, intersection-strict, intersection-
                        nonempty; default: union)
  -o SAMOUT, --samout=SAMOUT
                        write out all SAM alignment records into an output SAM
                        file called SAMOUT, annotating each line with its
                        feature assignment (as an optional field with tag
                        'XF')
  -q, --quiet           suppress progress report

Written by Simon Anders (sanders@fs.tum.de), European Molecular Biology
Laboratory (EMBL). (c) 2010. Released under the terms of the GNU General
Public License v3. Part of the 'HTSeq' framework, version 0.6.0.

I did not have a dash between nonunique and all, but I tried that too just in case. And I tried it with no space, and a –n, etc. Everything I could think of.

login4->[/projects/scratch/skcm/ARPE19/RNA]$ htseq-count -f bam -r pos -s reverse -t transcript -i transcript_id --nonunique all ARPE19_RNA_Control01.starAli.90.gtf >> Control_01.reverse.transcript.counts.txt
Usage: htseq-count [options] alignment_file gff_file

htseq-count: error: no such option: --nonunique

Thank you,

Dave

**Comment by iosonofabio** [comment]
That's not how pip works, please read the pip manual. Upgrade htseq and it'll work

pip install HTSeq==0.10.0

Cheers
Fabio

**Comment by dws23** [comment]
Oh, ok. Thank you.

Sent from my iPhone

On May 11, 2018, at 11:12 PM, Fabio Zanini <notifications@github.com<mailto:notifications@github.com>> wrote:

That's not how pip works, please read the pip manual. Upgrade htseq and it'll work

pip install HTSeq==0.10.0

Cheers
Fabio
