### ISSUE TITLE
AttributeError, raised in _HTSeq.pyx:1358

### ISSUE THREAD

**Issue by sentausa** [simon-anders/htseq#57]
Hi simon-anders,

I'm using htseq-count 0.9.1 on conda and I got this error when I tried to use it on a sorted, indexed bam file (using bowtie2 2.3.0 with --sensitive-local --trim5 10 followed by samtools 1.7 view -1 -bS and samtools sort, then samtools index):

`$htseq-count -f bam -r pos -t gene -i ID -s no sample.sort.bam genome.gff`
`5337 GFF lines processed.`
`100000 SAM alignment record pairs processed.`
`200000 SAM alignment record pairs processed.`
`Error occured when processing SAM input (record #416636 in file sample.sort.bam):`
`  'NoneType' object has no attribute 'encode'`
`  [Exception type: AttributeError, raised in _HTSeq.pyx:1358]`

It is similar to [this](https://www.biostars.org/p/318241/) unanswered question on Biostars.

I will appreciate any help on this.

Thanks.

**Comment by iosonofabio** [comment]
Hi,

First thing please update htseq, thanks
Fabio

**Comment by sentausa** [comment]
Hi Fabio,
Thanks for answering. Unfortunately, I couldn't find htseq higher than 0.9.1 on conda. No hope?

Thanks again

**Comment by iosonofabio** [comment]
Hi,

Use pip
Fabio

**Comment by sentausa** [comment]
Hi again,

This is what showed up when I typed pip install HTSeq:

`Requirement already satisfied: HTSeq in /Share/conda_envs/tsu/lib/python3.6/site-packages`
`Requirement already satisfied: numpy in /Share/conda_envs/tsu/lib/python3.6/site-packages (from HTSeq)`
`Requirement already satisfied: pysam>=0.9.0 in /Share/conda_envs/tsu/lib/python3.6/site-packages (from HTSeq)`

Thanks again.

**Comment by iosonofabio** [comment]
Please learn your pip:

pip install HTSeq==0.10.0

**Comment by iosonofabio** [comment]
No answer for a month, I assume this was an issue of using an obsolete version of htseq. Feel free to reopen if still relevant.
