### ISSUE TITLE
Do not automatically add "[part]" or "revcomp_of_" to name when slicing a segment or using get_reverse_complement()

### ISSUE THREAD

**Issue by woodword** [simon-anders/htseq#58]
When I try to slice a segment or use get_reverse_complement() in HTSeq, it will add an unnecessary "[part]" or "revcomp_of_" to the name and I have to write extra code to remove them. I don't think this is a practical function.

**Comment by iosonofabio** [comment]
I added an optional argument in the latest commit: 89f12460eb5bcf7b13478d6e056acd011508106b

Thanks for reporting.
