### ISSUE TITLE
Trouble installing HTSeq (python 3.5) on Mac

### ISSUE THREAD

**Issue by Suzanne11** [simon-anders/htseq#60]
Hello,

I am new with python , and trying to install HTSeq on my Mac.
Before I started I have installed xcode and numpy: 1.14.5.

I figured I first need to install pysam, the step I am stuck right now.

pip install pysam

Command "/Users/suzanne/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/yp/vd8kgzyj00x4b5dzcq4_vghh0000gn/T/pip-install-b8sgc50v/pysam/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/yp/vd8kgzyj00x4b5dzcq4_vghh0000gn/T/pip-record-u3cbv062/install-record.txt --single-version-externally-managed --compile --install-headers /Users/suzanne/env/include/site/python3.7/pysam" failed with error code 1 in /private/var/folders/yp/vd8kgzyj00x4b5dzcq4_vghh0000gn/T/pip-install-b8sgc50v/pysam/

pip install HTSeq

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/yp/vd8kgzyj00x4b5dzcq4_vghh0000gn/T/pip-install-eirjc94y/HTSeq/

Can someone help me out?

Thanks in advance!

**Comment by iosonofabio** [comment]
HTSeq on OSX is only tested for Python 2.7 and 3.6, please update your Python.
