### ISSUE TITLE
installation issue?

### ISSUE THREAD

**Issue by ChVav** [simon-anders/htseq#61]
Hi,

I am not sure how to fix the following problem on Ubuntu 16.04.
I installed HTSeq and the necessary dependencies using pip install.
When I try to run htseq-count I get following error:
Traceback (most recent call last):
  File "/home/opt/anaconda/bin/htseq-count", line 3, in <module>
    import HTSeq.scripts.count
  File "/home/opt/anaconda/lib/python2.7/site-packages/HTSeq/__init__.py", line 12, in <module>
    from _HTSeq import *
  File "__init__.pxd", line 164, in init HTSeq._HTSeq
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

is this a common issue? 

Thanks in advance!

**Comment by iosonofabio** [comment]
Hi ChVav,

Sorry for the late reply. Seems like you are compiling from source. That should not be necessary as I already transpile and compile everything for you on Travis during CI/CD.

Closing as binaries are available, please reopen the issue if you are still having issues.
