### ISSUE TITLE
htseq input bam format

### ISSUE THREAD

**Issue by thkitapci** [simon-anders/htseq#7]
Hi,
I think htseq requires bam file to be name sorted is that correct ? If I input a coordinate sorted bam file will I get a warning or error ? 

Thanks
Best Regards
Hamdi

**Comment by iosonofabio** [comment]
@thkitapci see the option -r: https://github.com/simon-anders/htseq/blob/master/HTSeq/scripts/count.py#L241-L245

The defaut is by name, so if you don't specify that option and input a coordinate-sorted file that's not great.
