### ISSUE TITLE
Htseq count with bed file

### ISSUE THREAD

**Issue by MoutonAlice** [simon-anders/htseq#73]
Dear Simon,
I have been asked to count the reads out of a customized bed files with around 900 coordinates. These coordinates do not always specifically match a gene id on my gtf file so I wanted to count the reads per coordinates. Reading the documentation, it seems that it is possible to customize the python script but before starting this, I want to be ure that it would be possible to do.  I can't find a lot of information on this. Maybe I can convert my bed to gtf and it will work. 
Would you have some suggestions?
Many thanks,
Best regards
Alice

**Comment by iosonofabio** [comment]
Hi Alice,

You can make up a GTF file or modify the htseq-count script, both ways will work.

Cheers
Fabio
