### ISSUE TITLE
Pysam 0.13.0 required on Mac, but not on Linux

### ISSUE THREAD

**Issue by fabio-t** [simon-anders/htseq#74]
Hi, you provide two Mac OS wheels and several Linux wheels on PiPy.

The Mac OS wheels have, inside the METADATA file, the following pysam requirement:

```
Requires-Dist: pysam (==0.13.0)
```

The Linux wheels, instead, have the following:

```
Requires-Dist: pysam (>=0.9.0)
```

Is there a reason for this? Having a fixed dependency version for pysam causes problems when other packages require newer versions.

**Comment by iosonofabio** [comment]
No good reason, in fact I just fixed it in commit a6ba1f4685efcf9b7b8ff2f52000f56d8b18286b
