### ISSUE TITLE
definition of 'too_low_aQual' and 'not_aligned' criteria

### ISSUE THREAD

**Issue by sandobits** [simon-anders/htseq#76]
I have a sample being mapped with hisat2 and tophat2. They yield considerably similar results, except in these two specific parameters:

tophat2:
> __no_feature	491048
__ambiguous	 459500
__too_low_aQual	 0
__not_aligned	 0
__alignment_not_unique	 2423556

hisat2:
>__no_feature	 495306
__ambiguous	 497703
__too_low_aQual	 244930
__not_aligned	 168542
__alignment_not_unique	 2729919

What is used to evaluate these two parameters, and why is tophat2's result equal 0?

**Comment by simon-anders** [comment]
"too low aQual" means that the alignment quality (5th column in a SAM file, a.k.a. "MAPQ") is below the user-chosen threshold

"not aligned" means that the read was reported but no alignment was found. I suppose that TopHat2 omits these reads from the SAM file.

**Comment by sandobits** [comment]
>"too low aQual" means that the alignment quality (5th column in a SAM file, a.k.a. "MAPQ") is below the user-chosen threshold

This was exactly what I was looking for. Thank you.
As a follow up, please consider adding information on the source of that value to the htseq documentation. Right now it only mentions the default threshold being 10 as of version 0.5.4.

**Comment by simon-anders** [comment]
If the documentation really doesn't say so, we should add it.

Hence reopening the issue to serve as reminder to do so.

**Comment by sandobits** [comment]
Admittedly, it does mention what it is, just not where it comes from: 

>-a <minaqual>, --a=<minaqual>
    skip all reads with alignment quality lower than the given minimum value (default: 10 — Note: the default used to be 0 until version 0.5.4.)

**Comment by iosonofabio** [comment]
Let's just improve that sentence a bit ;-)

**Comment by iosonofabio** [comment]
Addressed this in  6f7d66e, closing
