### ISSUE TITLE
 HTSeq==0.6.1p1 Installation broken

### ISSUE THREAD

**Issue by Zethson** [simon-anders/htseq#77]
Hi,

for an older pipeline I need a specific HTSeq version: HTSeq==0.6.1p1
However, the setup.py is broken:

pip install HTSeq==0.6.1p1
Collecting HTSeq==0.6.1p1
  Using cached https://files.pythonhosted.org/packages/3c/6e/f8dc3500933e036993645c3f854c4351c9028b180c6dcececde944022992/HTSeq-0.6.1p1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y4i_1377/HTSeq/setup.py", line 12, in <module>
        if sys.version_info[0] < 2 or sys.version_info < 5:
    TypeError: '<' not supported between instances of 'sys.version_info' and 'int'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-y4i_1377/HTSeq/

**Comment by iosonofabio** [comment]
Hi,

May I ask why you need that old version? I fixed many bugs since and I assume you don't want to have wrong results out of your sequencing?

I'm afraid fixing such old versions is a low priority for me, sorry.
Fabio

**Comment by Zethson** [comment]
It's specifically requested for https://github.com/aryeelab/guideseq
Since it's a rather big workflow I'm afraid that it depends on the old version (also for reproducibility's sake. But I'll try and see how far I can get..

**Comment by iosonofabio** [comment]
Python 2.7 will be deprecated next year, so I advise you to stop using it, but yeah, your mileage may vary...

**Comment by Zethson** [comment]
I'm actually planning to replace it with something more modern, but for that I have to investigate how it works and what results it produces first...
