### ISSUE TITLE
[howTo] Access GenomeArray() using a GenomeInterval() with a negative start

### ISSUE THREAD

**Issue by shouldsee** [simon-anders/htseq#81]
I was trying to __iadd__ a `GenomicArray()` with a `GenomicInterval()` at negative start, and got the following error. How much effort would it take to make GenomicArray() support negative index?

```python
arr = HTSeq.GenomicArray(chroms='auto')
iv = HTSeq.GenomicInterval('chr1',-10,50,'+')
arr[iv] += 1
```

```python

IndexErrorTraceback (most recent call last)
<ipython-input-257-5253053be354> in <module>()
      1 arr = HTSeq.GenomicArray(chroms='auto')
      2 iv = HTSeq.GenomicInterval('chr1',-10,50,'+')
----> 3 arr[iv] += 1

python2/src/HTSeq/_HTSeq.pyx in HTSeq._HTSeq.GenomicArray.__getitem__()

python2/src/HTSeq/_HTSeq.pyx in HTSeq._HTSeq.ChromVector.__getitem__()

IndexError: start too small
```

**Comment by shouldsee** [comment]
NVM. I found a solution using `HTSeq.StepVector.StepVector()` instead. It may be benefical to subclass `GenomicArray()` to allow negative indexing.

```python
iv = HTSeq.GenomicInterval('chr1',-5,30,'+')
vct = HTSeq.StepVector.StepVector.create(length=60,start_index=-10)
vct[iv.start:iv.end] +=1
list(vct)
```

**Comment by shouldsee** [comment]
Is HTSeq under active development at the moment?

**Comment by iosonofabio** [comment]
Yes, but we're not paid so PRs are welcome 😊

**Comment by iosonofabio** [comment]
@shouldsee It seems like you found a workaround, would you like to try and see how to add negative indexing to GenomicArray or should I close this?

**Comment by shouldsee** [comment]
It was only for plotting purposes and the StepVector worked fine so I think we can just add this Tip somewhere: *Use StepVector()* if you are dealing with negative index. 

I ended up plotting segments without a unified iterator so I don't really need this functionality anymore. But always good to save the snippet as an example.

**Comment by iosonofabio** [comment]
sounds good. where in the docs would you add it?

**Comment by shouldsee** [comment]
How about https://github.com/simon-anders/htseq/blob/master/python2/doc/genomic.rst

**Comment by shouldsee** [comment]
I will be PR in 5 mins

**Comment by iosonofabio** [comment]
Awesome thanks

**Comment by iosonofabio** [comment]
This got implemented meanwhile - I mentioned you in the history changes. Closing
