### ISSUE TITLE
Question about backend of default option -t

### ISSUE THREAD

**Issue by gtollefson** [simon-anders/htseq#83]
Hello,

When running htseq-count using default -t <feature_type> option to count reads that fall within exonic regions, does htseq make counts based upon only the first exon or the last exon for each gene **that has multiple exons annotated in the GFF3 file**. **Or does it count all reads that align in either of the exonic regions recorded?**

I am running htseq-count using a GFF3 file that has multiple exon records for a group of a genes and would like to use feature lengths to normalize my counts, but am not sure which to use when there are two exon records for one gene.

I've included a screenshot of such a record.

![Screen Shot 2019-05-09 at 2 51 10 PM](https://user-images.githubusercontent.com/32968172/57478838-f50e5300-7269-11e9-8d1f-461b3f6c0ead.png)

**Comment by iosonofabio** [comment]
Usually people take all exons from each gene and sum over them, but you can separate by exon if you want.

Normalizing by feature length is often not as useful as you might think, but not forbidden either. You probably want to get an idea of which isoforms are actually used and divide by something like the average length of a transcript from any of those isoforms.

RNA-Seq can be tough at times...

**Comment by fburdet** [comment]
Hello,

About the default option -t exon: I am indeed using a GTF from Ensembl, so I always used this option.

Now, I realised that if I do a colSums (in R) of the reads per sample counted by htseq-count, including the "___" stats, I get about twice as many reads as the number of mapped reads.
So this means that some reads are counted several times! 
How does it work? Does it do the sum of all exons of all transcripts, even if redundant? So if a gene has 10 isoforms, and 1 exon is common to the 10, the number counted by htseq-count for that exon is x10 for the "by gene" final output?
If so, isn't that a bit dangerous, given that we have no idea if the transcripts are actually expressed, and how much...

Been looking up the web about that, didn't find an answer.

Can you please enlighten me?

Thanks in advance!

**Comment by simon-anders** [comment]
No, each uniquely mapped read is counted only once.

The discrepancy in the colSum stems from the multi-mappers, i.e., the count for "__alignment_not_unique": this counter counts the number of alignments, not the number of reads. Hence, reads are overcounted there.

So. the column sum over everything should equal the number of alignment lines in your SAM file. The column sum over everything except for "__alignment_not_unique" and "__not_aligned" should equal the number of SAM lines with unique alignments (i.e., with "NH:i:1").

**Comment by fburdet** [comment]
Ah yes, thanks for the answer. Makes sense. I could check it works with my data for single end data.

However, for paired end, I get a factor of about 2 (just below) between the mapped reads (log from STAR 2.6.0c) and htseq-count 0.9.1 (sum of all fields except __alignment_not_unique, __not_aligned is always == 0)

I'm using the Aligned.sortedByCoord bam, which I realize might not be what is requested... but I don't get any error or warning. 

Any idea what's happening? Is it counting R1 and R2?

**Comment by simon-anders** [comment]
hsteq-count counts fragments, not reads. Typically, each fragment will have one R1 and one R2, and htseq-count checks that they both map to the same gene.

**Comment by fburdet** [comment]
Yes, that's what I understood, but obviously I have a problem as I have nearly twice as many counts from htseq-count as I have mapped reads from STAR. So it seems htseq-count is counting the reads, not fragments, in my case.

What am I doing wrong? 
It is stranded paired, so I'm using --stranded=reverse on a bam sorted by coordinates.

**Comment by simon-anders** [comment]
That's odd. Try sorting on read name. Also: any warnings issued by htseq-count?

**Comment by fburdet** [comment]
Ah yes:
Warning: 60939760 reads with missing mate encountered.
That's nearly twice the number of fragments (33206810)

So bad sorting?

**Comment by iosonofabio** [comment]
We have an open issue with bam files sorted by position, which is slightly less obvious to fix than it should be.

Please try sort by name and repeat.

**Comment by fburdet** [comment]
Yes, it does work after sorting by name instead of coordinate.

Thanks for your help.

**Comment by iosonofabio** [comment]
Thank you, that is useful indeed

**Comment by iosonofabio** [comment]
Closing as this is related solely to problems with the buffer when sorting by coordinate.
