### ISSUE TITLE
GenomicInterval.xrange(step = 1) cannot work in python3 

### ISSUE THREAD

**Issue by chaigsh** [simon-anders/htseq#88]
Dear author,
I found GenomicInterval.xrange(step = 1) cannot work in python3, but it woks well in python2.

Thanks

**Comment by chaigsh** [comment]
If I use this function [GenomicInterval.xrange(step = 1)] in python3, how to do it?

**Comment by chaigsh** [comment]
In Python3, I got one error: 
    for position in iv.xrange(step = 1):
AttributeError: 'HTSeq._HTSeq.GenomicInterval' object has no attribute 'xrange'

**Comment by iosonofabio** [comment]
This was a legit bug, fixed in commit c56cf6c, will be released in 0.11.5
