### ISSUE TITLE
htseq hates my gtf

### ISSUE THREAD

**Issue by ktadler** [simon-anders/htseq#90]
Hi SImon
i am having a problem runnig the htseq quantification on a bam built using STAR 2.6.0a and a GTF file

i am trying to quantify the bam using the same GTF file as for genome indexes,
but it fails, giving me this ERROR

Error occured when processing GFF file (line 1 of file my.gtf):
need more than 1 value to unpack

the gtf looks like this:

NC_001348.1 RefSeq CDS 173 562 . + 0 transcript_id "gene0"; gene_id "gene0"; gene_name "ORF0";
NC_001348.1 RefSeq CDS 589 915 . - 0 transcript_id "gene1"; gene_id "gene1"; gene_name "ORF1";
NC_001348.1 RefSeq CDS 1185 1850 . + 0 transcript_id "gene2"; gene_id "gene2"; gene_name "ORF2";
NC_001348.1 RefSeq CDS 1908 2447 . - 0 transcript_id "gene3"; gene_id "gene3"; gene_name "ORF3";

anf the command line is:

htseq-count -m   intersection-nonempty -s yes -f bam -r pos CONTROLDAY3.rep1.vzvAligned.sortedByCoord.out.bam my.gtf > ../htseq_counts_vzv/CONTROLDAY3.rep1.vzv.txt &

what could be probably my problem?

thanks,
katy

**Comment by simon-anders** [comment]
Are you sure that's tabs between the columns and not spaces?

**Comment by ktadler** [comment]
now i am sure they ARE spaces

[matrix] rong 351 : sed "s/\t/=/g" my.gtf | head -n 4
NC_001348.1     RefSeq  CDS     173     562     .       +       0
transcript_id "gene0"; gene_id "gene0"; gene_name "ORF0";
NC_001348.1     RefSeq  CDS     589     915     .       -       0
transcript_id "gene1"; gene_id "gene1"; gene_name "ORF1";
NC_001348.1     RefSeq  CDS     1185    1850    .       +       0
transcript_id "gene2"; gene_id "gene2"; gene_name "ORF2";
NC_001348.1     RefSeq  CDS     1908    2447    .       -       0
transcript_id "gene3"; gene_id "gene3"; gene_name "ORF3";
[matrix] rong 352 : sed "s/ /=/g" my.gtf | head -n 4
NC_001348.1=====RefSeq==CDS=====173=====562=====.=======+=======0=======transcript_id="gene0";=gene_id="gene0";=gene_name="ORF0";
NC_001348.1=====RefSeq==CDS=====589=====915=====.=======-=======0=======transcript_id="gene1";=gene_id="gene1";=gene_name="ORF1";
NC_001348.1=====RefSeq==CDS=====1185====1850====.=======+=======0=======transcript_id="gene2";=gene_id="gene2";=gene_name="ORF2";
NC_001348.1=====RefSeq==CDS=====1908====2447====.=======-=======0=======transcript_id="gene3";=gene_id="gene3";=gene_name="ORF3";

cool, thanks

‫בתאריך יום ה׳, 19 בספט׳ 2019 ב-15:00 מאת ‪Simon Anders‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by ktadler** [comment]
it indeed works now,
thanks

**Comment by simon-anders** [comment]
Great, then I can close the issue.

When changing the spaces to tabs, just remember that within the attribute column, i.e., from "transcript_id" onwards, you don't want tabs, because all this counts as one column: https://www.ensembl.org/info/website/upload/gff.html
