### ISSUE TITLE
Support pickling for SAM_Alignment object

### ISSUE THREAD

**Issue by saksham219** [simon-anders/htseq#94]
I need to iterate over reads in a BAM file and parallelising this is not possible currently as multiprocessing in python only works for objects that can be pickled. I don't know if there is a workaround for this.

**Comment by iosonofabio** [comment]
That seems to be an issue for `pysam` more than `HTSeq`.

In any case, there are many ways to address this indirectly. You can pickle the read name, the read number, the serialized version of the part of the record you care about (e.g. sequence/name/quality), etc.

Might come back to this when I implement multiprocessing for htseq-count, which should be soon given the pandemic extra stay-home time. Closing.
