### ISSUE TITLE
KeyError: 'Non-stranded index used for stranded GenomicArray.'

### ISSUE THREAD

**Issue by brobr** [simon-anders/htseq#96]
Hi, I am trying to use HTSeq from Jupyter-notebook, following the examples given in the documentation. 

In order to quantify differences between wild type and mutations affecting the process studied,
I've created "myowngtf"  a gtf mimicking the 'official' gtf but based on our own data as most of the features of interest are not annotated in that 'official' gtf.

I do not understand why, but It goes wrong on this snippet (which worked when using the 'official' gtf in a test-run):
>gtf_file = HTSeq.GFF_Reader(myowngtf)
exons = HTSeq.GenomicArrayOfSets( "auto", stranded=True )
>
>for feature in gtf_file:
     if feature.type == "exon":
        exons[ feature.iv ] += feature.attr["gene_id"]
>
Which throws this error:

>KeyError                                  Traceback (most recent call last)
<ipython-input-60-c561eb488466> in <module>
      7 for feature in gtf_file:
      8     if feature.type == "exon":
----> 9         exons[ feature.iv ] += feature.attr["gene_id"]
>
>
>python3/src/HTSeq/_HTSeq.pyx in HTSeq._HTSeq.GenomicArray.\__getitem\__()
>
>KeyError: 'Non-stranded index used for stranded GenomicArray.'

If I change 'feature.type == "exon" to something else, say "gene","CDS", "source", no error is thrown and -of course- nothing gets counted (as I end with an empty set).

And if I change `stranded=True` to `stranded=False` no error is thrown either and I do get stuff counted. But why? And why cannot `stranded = True` be used, when the info/data is stranded??? 

myowngtf  produces this output using the HTSeq defined gtf_file

>for feature in itertools.islice( gtf_file, 10 ):
    print(feature)
> <GenomicFeature: exon '1_nu_154' at 1: 24798 -> 24643 (strand '-')>
<GenomicFeature: exon '1_u_e_3utrCNA00170_290' at 1: 53970 -> 54261 (strand '+')>
<GenomicFeature: exon '1_u_s_e_helitron_1545' at 1: 496548 -> 498094 (strand '+')>
<GenomicFeature: exon '1_u_s_e_CNA02125_195' at 1: 561744 -> 561940 (strand '+')>
<GenomicFeature: exon '1_u_s_e_CNA02125_1413' at 1: 561940 -> 563354 (strand '+')>
<GenomicFeature: exon '1_nu_s_CNA02205_1160' at 1: 576269 -> 577430 (strand '+')>

**Comment by simon-anders** [comment]
Maybe put a `print(feature.iv)` right below the `if` statement, to see whether there is strand in `feature.iv` or not. Perhaps, the strand is missing in one of the exon lines?

**Comment by brobr** [comment]
Fabulous; thanks for that! One typo in the word that indicated strandedness near the end of the whole file that I used as basis for myowngtf!
