### ISSUE TITLE
Error in documentation describing coordinate conversion for GFF_Reader

### ISSUE THREAD

**Issue by marykthompson** [simon-anders/htseq#98]
Hi,

I believe the text below is wrong because to convert Ensembl 1-based, end included coordinates to Python coordinates you only need to subtract one from start coordinate, but not the end coordinate. i.e. 
[1, 100] -> [0, 100)

https://htseq.readthedocs.io/en/release_0.11.1/features.html#gff-reader-and-genomicfeature
"GFF_Reader will convert the coordinates from GFF standard (1-based, end maybe included) to HTSeq standard (0-base, end not included) by subtracting 1 from the start position, and, for end_included=True, also subtract 1 from the end position."

This says that you are also subtracting 1 from the end position if end_included = True, which I believe is not correct and also thankfully does not seem to be what GFF_Reader does. Just a small thing but letting you know because it confused me and led me to go checking for off-by-one errors. Thanks.

**Comment by iosonofabio** [comment]
@marykthompson you are right, I updated the docs now in commit 4021c20. Closing
