### ISSUE TITLE
Where is Windows installer of HTSeq.

### ISSUE THREAD

**Issue by vivekruhela** [simon-anders/htseq#99]
As per the documentation of HTSeq, the windows installer is avaialble at [HTSeq download page](https://pypi.org/project/HTSeq/#files) but when I checked it, I see `.whl` files for only linux and macOS.  Can anyone suggest me how to install htseq in windows or where is the windows installer of htseq. Thanks.

**Comment by iosonofabio** [comment]
Thanks for asking. I don't have a Windows machine so at the moment only osx and Linux are supported.

If you manage to install it on Win, please let me know how do I can add it to the docs

**Comment by vivekruhela** [comment]
Thanks for the reply. Is this tool written in C or in python?

**Comment by iosonofabio** [comment]
Both

**Comment by vivekruhela** [comment]
While building this tool in MinGw64, I am getting an error of `missing thread.h` and `c++11 compiler is requrired` (screenshot attached)
![Screenshot (96)](https://user-images.githubusercontent.com/13174913/77038629-42a33280-69da-11ea-9f74-d4f458b4d0b8.png)
. I think I am using I am using latest GCC compiler so `c++11`  error should not come (Am I wrong!!). Can you suggest me  how to get `thread.h` for my window-based compiler. Thanks.

**Comment by iosonofabio** [comment]
As mentioned, I don't have Windows so I can't help you to well. But try and make sure your GCC supports c++11. What version of gcc are you using?

**Comment by vivekruhela** [comment]
Here is the gcc version:

    $ gcc --version
    gcc.exe (Rev1, Built by MSYS2 project) 9.3.0

**Comment by iosonofabio** [comment]
I'm not sure how to help you since I don't have minigw or windows myself. In any case, `thread.h` seems like a very basic header file and is not related directly to HTSeq. Indeed, the compiler is trying to get some perl thing done for bcftool so it seems like you are reporting the issue for the wrong package.

Closing
